import React, { useState, useEffect } from 'react';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { Video, Download, FileText, Phone } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import axios from 'axios';

export const Telehealth = () => {
    const { user } = useAuth();
    const [inCall, setInCall] = useState(false);
    const [roomName, setRoomName] = useState('');

    useEffect(() => {
        // Generate a random unique room name for security
        // In production, this would be generated by the backend with an appointment ID
        setRoomName(`SilentDisease-${Math.random().toString(36).substring(7)}`);
    }, []);

    const startConsultation = () => {
        setInCall(true);
    };

    const exportData = async () => {
        try {
            // Fetch all health data
            const res = await axios.get(`http://localhost:5000/api/analytics/forecast/${user?._id}`, {
                 headers: { Authorization: `Bearer ${user?.token}` }
            });
            
            const history = res.data.history || [];
            
            // Convert to CSV
            const headers = ["Date", "RiskScore"];
            const csvRows = [headers.join(',')];
            
            history.forEach((row: any) => {
                csvRows.push(`${row.date},${row.risk}`);
            });
            
            const csvString = csvRows.join('\n');
            const blob = new Blob([csvString], { type: 'text/csv' });
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.setAttribute('hidden', '');
            a.setAttribute('href', url);
            a.setAttribute('download', `health_data_${user?.name}.csv`);
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
        } catch (err) {
            alert("Failed to export data");
        }
    };

    return (
        <div className="space-y-6 h-[calc(100vh-100px)] flex flex-col">
            <div className="flex justify-between items-center">
                <div className="flex items-center gap-3">
                    <div className="p-3 bg-primary/20 rounded-xl text-primary">
                        <Video size={32} />
                    </div>
                    <div>
                        <h1 className="text-3xl font-bold">Telehealth Consultation</h1>
                        <p className="text-gray-400">Secure, encrypted video calls with your healthcare provider.</p>
                    </div>
                </div>
                
                <Button variant="outline" onClick={exportData}>
                    <Download size={18} className="mr-2" /> Export My Data (CSV)
                </Button>
            </div>

            {inCall ? (
                <Card className="flex-1 overflow-hidden relative border-primary/30">
                     <iframe 
                        allow="camera; microphone; fullscreen; display-capture; autoplay"
                        src={`https://meet.jit.si/${roomName}#config.prejoinPageEnabled=false`}
                        style={{ height: '100%', width: '100%', border: 'none' }}
                        title="Jitsi Meet"
                     />
                     <Button 
                        variant="ghost" 
                        className="absolute top-4 right-4 bg-red-500 hover:bg-red-600 text-white"
                        onClick={() => setInCall(false)}
                     >
                        <Phone size={18} className="mr-2 rotate-135" /> End Call
                     </Button>
                </Card>
            ) : (
                <Card className="flex-1 flex flex-col items-center justify-center text-center p-12 border-dashed border-white/10 bg-transparent">
                    <div className="w-24 h-24 rounded-full bg-primary/10 flex items-center justify-center mb-6 text-primary">
                        <Video size={48} />
                    </div>
                    <h2 className="text-2xl font-bold mb-2">Ready for your appointment?</h2>
                    <p className="text-gray-400 max-w-md mb-8">
                        Your data is ready to be shared. Click below to start a secure video session. No extra accounts needed.
                    </p>
                    <div className="flex gap-4">
                        <Button size="lg" onClick={startConsultation} className="px-8">
                            <Video size={20} className="mr-2" /> Start Urgent Consultation
                        </Button>
                        <Button size="lg" variant="outline" onClick={exportData}>
                            <FileText size={20} className="mr-2" /> Download Medical Report
                        </Button>
                    </div>
                    <p className="mt-8 text-sm text-gray-500">
                        * Powered by Jitsi Meet (Open Source, End-to-End Encrypted)
                    </p>
                </Card>
            )}
        </div>
    );
};
